### PR TITLE
Project cleanup

### PR DESCRIPTION
**Pull request by sgdc3**
- Enhanced the maven project structure
- Removed eclipse project files
- Enhanced the .gitignore config

### CODE REVIEW

**Comment by walrusone** [comment]
Thanks for the cleanup, long overdue!

**Comment by sgdc3** [comment]
uh, damn merge conflicts, i'm sorry @walrusone

**Comment by walrusone** [comment]
No problem, I have it resolved now. I was working on adding team mode. My fault for not keeping the git current LOL

**Comment by walrusone** [comment]
Only found one issue so far, you imported the Spigot-API into all of the NMS classes. This created access to methods that aren't available across all versions (especially in 1.8 builds)

**Comment by sgdc3** [comment]
@walrusone we can just remove it, won't provide javadocs and source code but i think it's fine.

**Comment by sgdc3** [comment]
@walrusone Also, i added SkyWarsReloaded to my build server: https://ci.codemc.org/job/Walrusone/job/SkyWarsReloaded/

You can login using the github oauth and edit your build job as you want ;)

**Pull request merged**
